### ISSUE TITLE
Weird error while running david on `babbel` repository

### ISSUE THREAD

**Issue by satazor** [alanshaw/david#109]
```
git clone https://github.com/moooji/babbel.git && cd babbel && david

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:417:13
    at String.replace (native)
    at envReplace (/usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:413:12)
    at parseField (/usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:391:7)
    at /usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:334:17
    at Array.forEach (native)
    at Conf.add (/usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:333:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/david/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/david/node_modules/npm/lib/config/core.js:321:10)
    at /usr/local/lib/node_modules/david/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
```

**Comment by satazor** [comment]
I'm getting this error on a couple of modules. After investigation, it seems that these repositories have a `.npmrc` file with a custom registry setting that expect NPM_TOKEN env var.
